// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// auc_cpp
double auc_cpp(NumericVector preds, NumericVector labels);
RcppExport SEXP _rtemis_auc_cpp(SEXP predsSEXP, SEXP labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type preds(predsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type labels(labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(auc_cpp(preds, labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtemis_auc_cpp", (DL_FUNC) &_rtemis_auc_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtemis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
